version: '3.7'
services:
  database:
    image: mariadb
    container_name: nextcloud_database
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      - lan
    volumes:
      - db:/var/lib/mysql

  nextcloud:
    depends_on:
      - database
    image: nextcloud
    container_name: nextcloud_app
    restart: unless-stopped
    environment:
      - MYSQL_HOST=database
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_URL}
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    networks:
      - lan
      - traefik_network
    volumes:
      - ${NEXTCLOUD_DATA_DIR}:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.nextcloud.entrypoints=web,websecure"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_URL}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=leresolver"
      - "traefik.http.middlewares.nextcloud.redirectRegex.permanent=true"
      - "traefik.http.middlewares.nextcloud.redirectRegex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud.redirectRegex.replacement=https://$${1}/remote.php/dav/"

  restic:
    depends_on:
      - nextcloud
    image: restic
    container_name: nextcloud_restic
    build:
      context: ./restic
      dockerfile: Dockerfile
      args:
        RESTIC_INIT_ARGS: $RESTIC_INIT_ARGS
        RESTIC_PASSWORD: $RESTIC_PASSWORD
    restart: unless-stopped
    volumes:
      - ${NEXTCLOUD_DATA_DIR}/data:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - RESTIC_REPOSITORY=$RESTIC_REPOSITORY
      - BACKUP_CRON=${RESTIC_BACKUP_CRON:-0 */6 * * *}
      - RESTIC_FORGET_ARGS=--prune --keep-last 10 --keep-daily 1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - MAILX_ARGS=-r '${RESTIC_SEND_MAIL}' -s 'Result of the last restic backup run' -S smtp='${NEXTCLOUD_SMTP_HOST}:${NEXTCLOUD_SMTP_PASSWORD}' -S smtp-use-starttls -S smtp-auth=login -S smtp-auth-user='${NEXTCLOUD_SMTP_NAME}' -S smtp-auth-password='${NEXTCLOUD_SMTP_PASSWORD}' '${RESTIC_DEST_MAIL}'

volumes:
  db:
  html:

networks:
  lan:
  traefik_network:
    external: true 
